/**
 * This code was generated by Builder.io.
 */
"use client";
import * as React from "react";

function MyComponent(props) {
  return (
    <>
      <Symbol
        className="flex flex-col relative shrink-0 box-border"
        symbol={{
          data: {},
        }}
      />
      <div className="h-[600px] overflow-hidden overflow-x-hidden overflow-y-hidden relative w-full">
        <img
          loading="lazy"
          srcSet="https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fd4a66864f0f1470da698014238fef995?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fd4a66864f0f1470da698014238fef995?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fd4a66864f0f1470da698014238fef995?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fd4a66864f0f1470da698014238fef995?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fd4a66864f0f1470da698014238fef995?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fd4a66864f0f1470da698014238fef995?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fd4a66864f0f1470da698014238fef995?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fd4a66864f0f1470da698014238fef995"
          alt=""
          className="aspect-video object-cover object-center w-full h-full"
        />
        <div className="items-center bg-black bg-opacity-30 text-white flex flex-col justify-center absolute text-center p-5 inset-0">
          <h1 className="text-5xl font-bold mb-5">Discover Your Style</h1>
          <p className="text-2xl mb-8">
            Shop high-quality essentials for men and women.
          </p>
          <a className="bg-black text-white text-xl font-bold no-underline transition-[background-color] duration-[0.3s] ease-[ease] delay-[0s] duration-[0.3s] transition-[background-color] px-8 py-4 rounded-[30px] border-white border-[none]">
            Shop Now
          </a>
        </div>
      </div>
    </>
  );
}